import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, Compass, ExternalLink, LoaderCircle, MapPin, Search, Send } from "lucide-react";
import { Link, useParams, useSearchParams } from "react-router-dom";
import { ContactForm } from "@/components/ContactForm";
import { cancelExternalApiWakeUp, hasExternalPublicApi, postToPublicApi, scheduleExternalApiWakeUp } from "@/lib/publicApi";
import { trpc } from "@/lib/trpc";
import { applyPageMeta } from "@/lib/seo";
import { findPage, findResource, findStory, locations, pages, resources, stories, type PageEntity } from "@/data/site";
import styles from "@/styles/Site.module.css";

function useTitle(title: string, description = "Independent enterprise intelligence perspectives, platforms and practical approaches for complex organizations.") {
  useEffect(() => { applyPageMeta({ title, description }); }, [title, description]);
}

const familyLabel: Record<PageEntity["family"], string> = { solutions: "Solutions", industries: "Industries", platforms: "AI Platforms", capabilities: "Capabilities", company: "Company" };

export function EntityPage() {
  const { family, slug } = useParams();
  const entity = pages.find((page) => page.family === family && page.slug === slug);
  useTitle(entity?.title ?? "Page not found", entity?.summary);
  if (!entity) return <NotFound />;
  const siblings = pages.filter((page) => page.family === entity.family && page.slug !== entity.slug).slice(0, 3);
  const isPlatform = entity.family === "platforms";
  return <>
    <section className={`${styles.entityHero} ${styles[`entity${entity.accent[0].toUpperCase()}${entity.accent.slice(1)}`]}`}>
      <div className={styles.entityHeroLines} aria-hidden="true"><i /><i /><i /></div>
      <div className={styles.entityHeroInner}><div className={styles.breadcrumbs}><Link to={`/${entity.family === "company" ? "company/about" : entity.family}`}>{familyLabel[entity.family]}</Link><span>/</span><span>{entity.slug.replaceAll("-", " ")}</span></div><span className={styles.entityKicker}>{entity.eyebrow}</span><h1>{entity.title}</h1><p>{entity.summary}</p><div className={styles.entityActions}><Link to="/contact">Talk through the opportunity <ArrowRight size={16} aria-hidden="true" /></Link>{isPlatform && <a href="#platform-faqs">Read common questions <ArrowRight size={16} aria-hidden="true" /></a>}</div></div>
      <div className={styles.entityGlyph} aria-hidden="true"><span>{entity.slug.split("-")[0].slice(0, 2)}</span><i /><i /><i /></div>
    </section>

    {isPlatform && <nav className={styles.sectionNav} aria-label="On this page"><a href="#overview">Overview</a><a href="#approach">How it works</a><a href="#resources">Perspectives</a><a href="#platform-faqs">FAQs</a><Link to="/contact">Request a conversation</Link></nav>}

    <section id="overview" className={styles.entityIntro}><div><span className={styles.eyebrow}>The point of view</span><h2>Move from fragmented activity to a connected path through the work.</h2></div><p>{entity.intro}</p></section>
    <section id="approach" className={styles.pillarSection}><div className={styles.pillarHeading}><span className={styles.eyebrow}>Built around the practical questions</span><h2>The work becomes clearer when each discipline has a role.</h2><p>We use these principles to guide the way teams understand the present, shape the next move and keep delivery connected to outcomes.</p></div><div className={styles.pillarList}>{entity.pillars.map((pillar, index) => <article key={pillar.title}><span>0{index + 1}</span><h3>{pillar.title}</h3><p>{pillar.body}</p><i /></article>)}</div></section>
    <section className={styles.entityOutcome}><div><span className={styles.eyebrow}>What it enables</span><h2>Purposeful change, built into the way teams work.</h2></div><div>{entity.outcomes.map((outcome) => <article key={outcome.value}><strong>{outcome.value}</strong><span>{outcome.label}</span></article>)}</div></section>
    <section id="resources" className={styles.relatedSection}><div className={styles.sectionHeaderWide}><div><span className={styles.eyebrow}>Continue exploring</span><h2>Connected perspectives for the next conversation.</h2></div><Link className={styles.textLink} to="/resources/blog">All perspectives <ArrowRight size={16} aria-hidden="true" /></Link></div><div className={styles.relatedCards}>{resources.slice(0, 3).map((resource) => <Link key={resource.slug} to={`/resources/blog/${resource.slug}`}><span>{resource.category} · {resource.date}</span><h3>{resource.title}</h3><ArrowRight size={16} aria-hidden="true" /></Link>)}</div></section>
    {isPlatform && <Faqs />}
    <section className={styles.siblingSection}><span className={styles.eyebrow}>Related {familyLabel[entity.family].toLowerCase()}</span><div>{siblings.map((sibling) => <Link key={sibling.slug} to={`/${sibling.family}/${sibling.slug}`}><span>{sibling.eyebrow}</span><strong>{sibling.title}</strong><ArrowRight size={16} aria-hidden="true" /></Link>)}</div></section>
    <CompactContact />
  </>;
}

function Faqs() {
  const [open, setOpen] = useState(0);
  const questions = [
    ["Where does an enterprise platform begin?", "A useful start is a bounded workflow with clear users, decisions, evidence and oversight. That creates an application teams can understand, evaluate and extend."],
    ["How does this connect to existing systems?", "The point is not to replace every system at once. We create a context layer that helps teams work across the platforms and data they already need to keep operating."],
    ["What makes a platform approach different?", "A platform approach creates reusable patterns for context, governance and delivery, allowing each new application to benefit from the learning and controls already in place."],
  ];
  return <section id="platform-faqs" className={styles.faqSection}><div><span className={styles.eyebrow}>Questions teams often ask</span><h2>A few useful places to start.</h2></div><div className={styles.faqList}>{questions.map(([question, answer], index) => <article key={question}><button type="button" onClick={() => setOpen(open === index ? -1 : index)} aria-expanded={open === index}>{question}<ChevronDown size={18} aria-hidden="true" /></button>{open === index && <p>{answer}</p>}</article>)}</div></section>;
}

export function PlatformsOverview() {
  useTitle("AI platforms", "Three platform perspectives for orchestrating intelligent workflows, changing critical software and running resilient operations.");
  const platformPages = pages.filter((page) => page.family === "platforms");
  return <><section className={styles.overviewHero}><span className={styles.eyebrow}>AI platforms</span><h1>Context is the system behind useful enterprise intelligence.</h1><p>Meet three platform perspectives for orchestrating intelligent workflows, changing critical software and running more resilient operations.</p><Link to="/contact">Explore the platform view <ArrowRight size={16} aria-hidden="true" /></Link></section><section className={styles.platformOverviewGrid}>{platformPages.map((page, index) => <Link to={`/platforms/${page.slug}`} key={page.slug} className={styles.platformOverviewCard}><span>0{index + 1} · {page.eyebrow}</span><h2>{page.title}</h2><p>{page.summary}</p><div><i /><i /><i /></div><b>Explore {page.slug} <ArrowRight size={16} aria-hidden="true" /></b></Link>)}</section><section className={styles.architectureStrip}><div><span className={styles.eyebrow}>A shared layer</span><h2>The enterprise context layer connects systems, knowledge and decisions.</h2></div><div className={styles.architectureNodes}><span>Systems</span><i /><span>Policies</span><i /><span>Data</span><i /><span>Workflows</span></div></section><CompactContact /></>;
}

export function FamilyOverviewPage() {
  const { family } = useParams();
  const validFamily = family === "solutions" || family === "industries" || family === "capabilities" ? family : undefined;
  const visiblePages = validFamily ? pages.filter((page) => page.family === validFamily) : [];
  const titles: Record<NonNullable<typeof validFamily>, { eyebrow: string; title: string; summary: string }> = {
    solutions: { eyebrow: "Solutions", title: "Build a path through the work that matters most.", summary: "Explore focused approaches for modernizing systems, connecting experiences, improving commerce and making intelligent workflows practical." },
    industries: { eyebrow: "Industries", title: "The best next move begins with the realities of your industry.", summary: "Every sector has its own operating constraints, customer expectations and moments where a clearer shared context can make a difference." },
    capabilities: { eyebrow: "Capabilities", title: "The disciplines that turn intent into enterprise momentum.", summary: "Bring strategy, product, experience, engineering and data into the same delivery conversation." },
  };
  if (!validFamily) return <NotFound />;
  const copy = titles[validFamily];
  useTitle(copy.eyebrow);
  return <><section className={styles.listingHero}><span className={styles.eyebrow}>{copy.eyebrow}</span><h1>{copy.title}</h1><p>{copy.summary}</p><Link to="/contact">Start with a conversation <ArrowRight size={16} aria-hidden="true" /></Link></section><section className={styles.collectionSection}><div className={styles.collectionHeading}><div><span className={styles.eyebrow}>Explore the work</span><h2>A connected set of perspectives for the enterprise in front of you.</h2></div></div><div className={styles.collectionGrid}>{visiblePages.map((page) => <Link key={page.slug} to={`/${page.family}/${page.slug}`} className={styles.collectionCard}><div className={`${styles.collectionArt} ${styles[page.accent]}`}><span>{page.eyebrow}</span><b>{page.slug.slice(0, 3)}</b><i /></div><span>{page.eyebrow}</span><h3>{page.title}</h3><p>{page.summary}</p><ArrowRight size={17} aria-hidden="true" /></Link>)}</div></section><CompactContact /></>;
}

export function StoriesPage() {
  useTitle("Customer stories", "Illustrative enterprise stories showing how context, capability and delivery can move together.");
  const [active, setActive] = useState("All");
  const sectors = ["All", ...Array.from(new Set(stories.map((story) => story.sector)))];
  const visibleStories = active === "All" ? stories : stories.filter((story) => story.sector === active);
  return <><section className={styles.listingHero}><span className={styles.eyebrow}>Customer stories</span><h1>Practical change, told through the work.</h1><p>These independently authored illustrative stories explore the kinds of progress teams can make when context, capability and delivery align.</p><Link to="/contact">Connect with us <ArrowRight size={16} aria-hidden="true" /></Link></section><section className={styles.featuredStory}><div><span className={styles.eyebrow}>Featured perspective</span><h2>{stories[0].title}</h2><p>{stories[0].summary}</p><Link className={styles.textLink} to={`/customers/stories/${stories[0].slug}`}>Read illustrative story <ArrowRight size={16} aria-hidden="true" /></Link></div><div className={styles.featuredArt}><span>Focus / Outcome / Operating rhythm</span><i /><i /><i /></div></section><section className={styles.collectionSection}><div className={styles.collectionHeading}><div><span className={styles.eyebrow}>Explore all stories</span><h2>Different work. Same focus on making the next move practical.</h2></div><div role="tablist" className={styles.filterTabs}>{sectors.map((sector) => <button key={sector} type="button" role="tab" aria-selected={active === sector} onClick={() => setActive(sector)}>{sector}</button>)}</div></div><div className={styles.collectionGrid}>{visibleStories.map((story) => <Link key={story.slug} to={`/customers/stories/${story.slug}`} className={styles.collectionCard}><div className={`${styles.collectionArt} ${styles[story.theme]}`}><span>{story.sector}</span><b>{story.slug.slice(0, 3)}</b><i /></div><span>Illustrative story</span><h3>{story.title}</h3><p>{story.summary}</p><ArrowRight size={17} aria-hidden="true" /></Link>)}</div></section><CompactContact /></>;
}

export function StoryDetailPage() {
  const { slug } = useParams();
  const story = findStory(slug ?? "");
  useTitle(story?.title ?? "Story not found", story?.summary);
  if (!story) return <NotFound />;
  return <><section className={styles.detailHero}><div><Link className={styles.backLink} to="/customers/stories"><ArrowLeft size={15} aria-hidden="true" /> Customer stories</Link><span className={styles.eyebrow}>{story.sector} · illustrative engagement</span><h1>{story.title}</h1><p>{story.summary}</p></div><div className={`${styles.detailArt} ${styles[story.theme]}`}><span>When context meets action</span><i /><i /><i /></div></section><section className={styles.detailSignals}>{story.signals.map((signal) => <div key={signal.label}><strong>{signal.value}</strong><span>{signal.label}</span></div>)}</section><section className={styles.detailNarrative}><div><span className={styles.eyebrow}>The challenge</span><h2>Complex work needs an operating view that teams can share.</h2></div><div><p>This illustrative scenario reflects a common enterprise pattern: teams see part of the system, but not enough of the whole to decide and act with confidence. The first step is not simply a new tool. It is a clearer shared understanding of the work, its constraints and the signals that matter.</p><p>By connecting those perspectives, teams can make smaller, more useful changes while preserving the evidence needed to improve the way work happens next.</p></div></section><section className={styles.detailApproach}><span className={styles.eyebrow}>A practical approach</span>{["Bring the scattered context into a usable view.", "Choose one workflow where better decisions will make a visible difference.", "Build the new rhythm into everyday delivery and learn from the result."].map((item, index) => <div key={item}><span>0{index + 1}</span><h3>{item}</h3></div>)}</section><CompactContact /></>;
}

export function ResourcesPage({ demoLibrary = false }: { demoLibrary?: boolean }) {
  useTitle(demoLibrary ? "Demo library" : "Perspectives", demoLibrary ? "Guided concept walkthroughs for teams exploring enterprise intelligence." : "Practical guides, research and field notes for people making enterprise change happen.");
  const [active, setActive] = useState("All");
  const types = ["All", "Article", "Research", "Guide"];
  const items = active === "All" ? resources : resources.filter((resource) => resource.category === active);
  return <><section className={`${styles.resourceHero} ${demoLibrary ? styles.demoHero : ""}`}><span className={styles.eyebrow}>{demoLibrary ? "Demo library" : "Perspectives"}</span><h1>{demoLibrary ? "Walk through the ideas behind context-first enterprise intelligence." : "Ideas from people shaping the work, not just the narrative."}</h1><p>{demoLibrary ? "A concise collection of guided concept walkthroughs for teams exploring practical applications." : "Practical guides, field notes and research perspectives for the people making enterprise change happen."}</p>{!demoLibrary && <NewsletterForm />}</section><section className={styles.resourceCollection}><div className={styles.collectionHeading}><div><span className={styles.eyebrow}>Explore all content</span><h2>{demoLibrary ? "Concept walkthroughs" : "A growing library of perspectives"}</h2></div>{!demoLibrary && <div role="tablist" className={styles.filterTabs}>{types.map((type) => <button type="button" key={type} role="tab" aria-selected={active === type} onClick={() => setActive(type)}>{type}</button>)}</div>}</div><div className={styles.resourceGrid}>{items.map((resource, index) => <Link key={resource.slug} to={`/resources/blog/${resource.slug}`} className={`${styles.resourceCard} ${styles[resource.theme]}`}><div><span>{resource.category}</span><b>0{index + 1}</b></div><h3>{resource.title}</h3><p>{resource.summary}</p><footer><span>{resource.date}</span><ArrowRight size={17} aria-hidden="true" /></footer></Link>)}</div></section><section className={styles.editorialCallout}><span className={styles.eyebrow}>A useful next read</span><h2>How to tell the difference between AI activity and AI capability.</h2><Link to="/resources/blog/an-enterprise-ai-decision-canvas">Read the decision canvas <ArrowRight size={16} aria-hidden="true" /></Link></section><CompactContact /></>;
}

export function NewsletterForm() {
  const [email, setEmail] = useState(""); const [state, setState] = useState<"idle" | "sending" | "success" | "error" | "duplicate">("idle"); const [waitingForBackend, setWaitingForBackend] = useState(false);
  const subscribe = trpc.site.newsletter.useMutation();
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!/^\S+@\S+\.\S+$/.test(email)) { setState("error"); return; } const duplicateKey = `sharavira-newsletter-${email.toLowerCase()}`; if (window.sessionStorage.getItem(duplicateKey)) { setState("duplicate"); return; } setState("sending"); setWaitingForBackend(false); const wakeUpTimer = scheduleExternalApiWakeUp(() => setWaitingForBackend(true)); try { const idempotencyKey = crypto.randomUUID(); if (hasExternalPublicApi()) { await postToPublicApi("/newsletter", { email }, idempotencyKey); } else { await subscribe.mutateAsync({ email, idempotencyKey }); } window.sessionStorage.setItem(duplicateKey, "1"); setState("success"); setEmail(""); } catch (error) { setState(error instanceof Error && /already received|duplicate/i.test(error.message) ? "duplicate" : "error"); } finally { cancelExternalApiWakeUp(wakeUpTimer); setWaitingForBackend(false); } };
  return <form className={styles.newsletterForm} onSubmit={submit} noValidate><label><span className="sr-only">Email address</span><input value={email} onChange={(event) => { setEmail(event.target.value); if (state !== "idle") setState("idle"); }} placeholder="Email address" inputMode="email" /></label><button type="submit" disabled={state === "sending" || subscribe.isPending}>{state === "sending" || subscribe.isPending ? "Subscribing" : <>Subscribe <Send size={15} aria-hidden="true" /></>}</button>{state === "sending" && waitingForBackend && <p className={styles.newsletterWakeup} role="status"><LoaderCircle className={styles.spinning} size={14} aria-hidden="true" /> Waking the subscription service. Please keep this page open.</p>}{state === "success" && <p role="status">You are on the list.</p>}{state === "duplicate" && <p role="status">This email is already subscribed.</p>}{state === "error" && <p role="alert">Enter a valid email address or try again.</p>}</form>;
}

export function ResourceDetailPage() {
  const { slug } = useParams(); const resource = findResource(slug ?? ""); useTitle(resource?.title ?? "Perspective not found", resource?.summary); if (!resource) return <NotFound />;
  return <><article className={styles.article}><header><Link className={styles.backLink} to="/resources/blog"><ArrowLeft size={15} aria-hidden="true" /> Perspectives</Link><span className={styles.eyebrow}>{resource.category} · {resource.date}</span><h1>{resource.title}</h1><p>{resource.summary}</p></header><div className={`${styles.articleHeroArt} ${styles[resource.theme]}`}><span>Point of view / Field note / Practical framework</span><i /><i /><i /></div><div className={styles.articleBody}><p className={styles.articleLead}>The organizations making useful progress with enterprise intelligence do not begin with a model. They begin with the work: the decisions, relationships and constraints that determine whether an idea can become a capability.</p><h2>Start with the context teams already carry.</h2><p>Context includes the systems people depend on, the data that supports a decision, the policies that set a boundary and the tacit knowledge that keeps work moving. When that context is scattered, even promising initiatives become difficult to evaluate and hard to scale.</p><p>A more practical approach makes the operating reality visible before it tries to automate it. It gives teams a common way to see the work, choose an initial intervention and understand what evidence will show whether it is helping.</p><blockquote>Useful enterprise intelligence amplifies the work people are already trying to do. It does not ask them to suspend their understanding of how the system actually operates.</blockquote><h2>Design the next move to learn something valuable.</h2><p>Instead of pursuing a broad transformation promise, focus a first application on one workflow where a clearer decision, faster response or more connected handoff will create useful evidence. Keep the boundaries clear and the learning loop close to the people doing the work.</p><Link to="/contact" className={styles.textLink}>Talk through a practical starting point <ArrowRight size={16} aria-hidden="true" /></Link></div></article><section className={styles.articleRelated}><span className={styles.eyebrow}>Keep exploring</span>{resources.filter((item) => item.slug !== resource.slug).slice(0, 2).map((item) => <Link key={item.slug} to={`/resources/blog/${item.slug}`}>{item.title}<ArrowRight size={16} aria-hidden="true" /></Link>)}</section></>;
}

export function SearchPage() {
  const [params, setParams] = useSearchParams(); const [query, setQuery] = useState(params.get("q") ?? ""); useTitle("Search");
  const entries = useMemo(() => [...pages.map((page) => ({ title: page.title, summary: page.summary, type: page.eyebrow, to: `/${page.family}/${page.slug}` })), ...stories.map((story) => ({ title: story.title, summary: story.summary, type: "Customer story", to: `/customers/stories/${story.slug}` })), ...resources.map((resource) => ({ title: resource.title, summary: resource.summary, type: resource.category, to: `/resources/blog/${resource.slug}` }))], []);
  const term = (params.get("q") ?? query).trim().toLowerCase(); const results = term ? entries.filter((entry) => `${entry.title} ${entry.summary} ${entry.type}`.toLowerCase().includes(term)) : entries.slice(0, 8);
  const submit = (event: FormEvent) => { event.preventDefault(); setParams(query.trim() ? { q: query.trim() } : {}); };
  return <section className={styles.searchPage}><span className={styles.eyebrow}>Search</span><h1>Find a useful way into the conversation.</h1><form onSubmit={submit}><Search size={20} aria-hidden="true" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search platforms, perspectives or approaches" /><button type="submit">Search</button></form><p className={styles.resultCount}>{term ? `${results.length} result${results.length === 1 ? "" : "s"} for “${params.get("q") ?? query}”` : "Browse recent topics and approaches"}</p><div className={styles.searchPageResults}>{results.map((entry) => <Link key={entry.to} to={entry.to}><span>{entry.type}</span><h2>{entry.title}</h2><p>{entry.summary}</p><ArrowRight size={17} aria-hidden="true" /></Link>)}</div></section>;
}

export function ContactPage() { useTitle("Let's connect", "Start a focused enterprise conversation about an opportunity, platform application or practical next step."); return <><section className={styles.contactHero}><div><span className={styles.eyebrow}>Let&apos;s connect</span><h1>Bring the question. We&apos;ll bring a useful point of view.</h1><p>Whether you are shaping a platform, modernizing a system or looking for a clearer way to move through the work, we would like to hear where you are starting.</p><div className={styles.contactHeroNotes}><span><Check size={15} aria-hidden="true" /> A short conversation, not a sales script</span><span><Check size={15} aria-hidden="true" /> A response based on your stated focus</span></div></div><div className={styles.contactPageForm}><span className={styles.eyebrow}>Get in touch</span><h2>What is the opportunity in front of you?</h2><ContactForm /></div></section></> }

export function CompanyOverview() { useTitle("Company"); return <><section className={styles.companyHero}><span className={styles.eyebrow}>About Sharavira Technology</span><h1>People, products and practical intelligence for the work ahead.</h1><p>We are an independent demonstration of how an enterprise consulting and platform experience can connect insight to delivery.</p></section><section className={styles.companyManifesto}><div><span className={styles.eyebrow}>Our approach</span><h2>The most meaningful change happens when the whole system is part of the work.</h2></div><div>{["Business direction", "Experience design", "Engineering quality", "Intelligent operations"].map((item, index) => <article key={item}><span>0{index + 1}</span><h3>{item}</h3><p>One connected discipline in the work of making progress durable.</p></article>)}</div></section><section className={styles.locationSection}><div><span className={styles.eyebrow}>Where we work</span><h2>One connected point of view, shaped by local context.</h2></div><div>{locations.map((location) => <article key={location.region}><MapPin size={18} aria-hidden="true" /><h3>{location.region}</h3><p>{location.cities.join(" · ")}</p></article>)}</div></section><CompactContact /></> }

export function PrivacyPage() { useTitle("Privacy and accessibility"); return <section className={styles.legalPage}><span className={styles.eyebrow}>Privacy and accessibility</span><h1>A clear, minimal approach to your information.</h1><p>This independent demonstration site stores only local browser preferences and example form entries in the current browser session. It does not add third-party advertising, analytics or chat tracking.</p><h2>Cookie preference</h2><p>If you dismissed the preference notice, that choice is stored locally in your browser. You can clear local storage in your browser settings to see it again.</p><h2>Accessibility</h2><p>The experience includes a skip link, keyboard-operable navigation, visible focus treatment, semantic landmarks, labeled inputs and reduced-motion support. If you find an accessibility barrier, please use the contact form to describe it.</p><h2>Reference and asset boundary</h2><p>This website is an independently authored educational recreation inspired by public information architecture and broad interface cues. It does not reuse the reference site’s source code, brand assets, client logos, third-party awards or long-form editorial content.</p></section> }

function CompactContact() { return <section className={styles.compactContact}><div><span className={styles.eyebrow}>A useful next step</span><h2>There is no substitute for understanding the work together.</h2></div><Link to="/contact">Let&apos;s connect <ArrowRight size={17} aria-hidden="true" /></Link></section> }

export function NotFound() { useTitle("Page not found"); return <section className={styles.notFound}><Compass size={36} aria-hidden="true" /><span className={styles.eyebrow}>404</span><h1>The page you are looking for has moved—or was never part of this path.</h1><p>Try a different route, explore a platform, or return to the home page.</p><div><Link to="/">Return home <ArrowRight size={16} aria-hidden="true" /></Link><Link to="/search">Search the site <Search size={16} aria-hidden="true" /></Link></div></section> }
